<?php

use App\Utils\MyReflectionUtils;

 foreach ($selection_props as $prop) { ?>
    <section>
        <?php

        $propName = $prop->getName();
        $strictValidation = ((isset($completeModel)) && ($completeModel === true));

        // variations for PK in case of Search OR AddItem
        if (($strictValidation) && (call_user_func([$selection_model, 'isPK'], $propName))) {
            // PK will be generated by the controller
            continue;
        }

        $propInfo = MyReflectionUtils::getValidationInfo($selection_model, $propName);

        $htmlType = '';
        $htmlMin = '';
        $htmlMax = '';
        $htmlReq = (($strictValidation) && ($prop->hasType()) && (!$prop->getType()->allowsNull()))? 'required' : '';
        $htmlPattern = ($strictValidation)? ('pattern="' . $this->e($propInfo[3]) . '"') : '';
        $htmlOpeningTag = '<input';
        $htmlClosingTag = '';

        switch ($propInfo[0]) {

            case 'int':
            case 'bcnum':
                $htmlType = 'type="number"';
                $htmlMin =  (ctype_digit($propInfo[1])) ? ('min="' . $propInfo[1] . '"') : '';
                $htmlMax =  (ctype_digit($propInfo[2])) ? ('max="' . $propInfo[2] . '"') : '';
                break;

            case 'url':
            case 'email': 
                $htmlType = 'type="' . (($strictValidation)? $propInfo[0] : 'text') . '"';
                break;

            case 'pwd':
                $htmlType = 'type="' . (($strictValidation) ? 'password' : 'text') . '"';
                $htmlMin =  (ctype_digit($propInfo[1]) && ($strictValidation)) ? ('minlength="' . $propInfo[1] . '"') : '';
                $htmlMax =  (ctype_digit($propInfo[2])) ? ('maxlength="' . $propInfo[2] . '"') : '';
                break;

            case 'tag':
                $htmlType = 'type="text"';
                break;

            case 'textarea':
                $htmlType = '';
                $htmlOpeningTag = '<textarea';
                $htmlClosingTag = '</textarea>';
                break;

            default:
                $htmlType = 'input type="text"';
                $htmlMin =  (ctype_digit($propInfo[1]) && ($strictValidation)) ? ('minlength="' . $propInfo[1] . '"') : '';
                $htmlMax =  (ctype_digit($propInfo[2])) ? ('maxlength="' . $propInfo[2] . '"') : '';
                break;
        }

        ?>

        <div class="adv_label"><label for="<?= $propName ?>"><?= $propName ?></label></div>
        <?= $htmlOpeningTag ?> <?= $htmlType ?> <?= $htmlMin ?> <?= $htmlMax ?> id="<?= $propName ?>" name="<?= $propName ?>" <?= $htmlPattern ?> <?= $htmlReq ?> placeholder="..." class="adv_field"><?= $htmlClosingTag ?>
    </section>
<?php } ?>